### ISSUE TITLE
Support for 2nd generation Execution Environment

### ISSUE THREAD

**Issue by fabrana** [GoogleCloudPlatform/terraform-google-cloud-run#151]
It would be helpful to allow setting the Cloud Run Execution Environment.

Terraform GCP provider supports the functionality:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#execution_environment

so exposing it in the module should be possible

**Comment by fabrana** [comment]
Still interested in this

**Comment by Azuka** [comment]
Bump

**Comment by prabhu34** [comment]
`google_cloud_run_service` the module was using this resource during the module development. 
`google_cloud_run_v2_service` is the latest resource for Cloud Run Gen 2.

**Comment by fabrana** [comment]
Thanks for the suggestion @prabhu34 

For the record, adding this to `module "cloud_run" { ...`
works
```
template_annotations = {
  ...
  "run.googleapis.com/execution-environment" = "gen2",
  ...
}
```
