### ISSUE TITLE
Module use DomainMappings, a preview feature

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/terraform-google-cloud-run#152]
This module helps users set up a domain while creating Cloud Run services. 

The DomainMapping feature of Cloud Run is a preview feature, it will unfortunately not reach GA and we are trying to steer users away from it.

The module should make this clear to users.

**Comment by steren** [comment]
This issue isn't obsolete

**Comment by steren** [comment]
still true

**Comment by pataquets** [comment]
Too bad Google is dropping this feature. It comes very handy. Is there another alternative other than shelling out the monthly fixed spend of the Google Load Balancer?

Sounds quite contradictory for a, serverless, pay-for-use product to need a fixed-cost component for providing external connectivity...

Is the feature discussion or roadmap public to check the rationale, in case users are mustang some important point?

Thanks!

**Comment by steren** [comment]
> Is there another alternative other than shelling out the monthly fixed spend of the Google Load Balancer?

yes, Firebase Hosting is free of charge: https://cloud.google.com/run/docs/mapping-custom-domains#firebase
