### ISSUE TITLE
Modules are not in sync with latest features from official TF reources

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/terraform-google-cloud-run#153]
The Cloud Run team produces official terraform resources for all Cloud Run resources. Every GA feature is guaranteed by design and process to be available in the terraform resource, [see TF docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service)

This module is not in sync with the latest features added to Cloud Run. For example: `containers` should now accept a list of containers.

It is unclear what the value of this module is, compared to the drawbacks of it not capturing all Cloud Run features.

At a minimum, I would suggest to point at the TF resource from this module README. So that users are aware they could directly use the TF resource.

**Comment by gueux** [comment]
@steren 
Im working on adding multicontainer support for cloud run module, you can check my progress [here](https://github.com/gueux/terraform-google-cloud-run/tree/multicontainer-support)
I'll appreciate your suggestions.

**Comment by steren** [comment]
ping
