### ISSUE TITLE
Cloud Run Job missing argument: encryption_key

### ISSUE THREAD

**Issue by maksymsereda** [GoogleCloudPlatform/terraform-google-cloud-run#172]
Hi,
it looks like the [encryption_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_job#encryption_key) argument is missing in Cloud Run Job terraform module. Is it possible to add as it was done in Cloud Run Service?

**Comment by prabhu34** [comment]
`google_cloud_run_service` the module was using this resource during the module development.
`google_cloud_run_v2_service` is the latest resource for Cloud Run Gen 2, where the `encryption_key` is supported.

**Comment by maksymsereda** [comment]
Hi @prabhu34, 
thank you for your response. But I think that we are talking about different things. I asked about Jobs, not Services

**Comment by prabhu34** [comment]
@maksymsereda Apologies. I confused the comment with other issue and misguided by `Is it possible to add as it was done in Cloud Run Service?`.
