### ISSUE TITLE
Add suport for selecting Cloud Run generation

### ISSUE THREAD

**Issue by Mistic92** [GoogleCloudPlatform/terraform-google-cloud-run#22]
There is available gen2 in preview which is not possible to select using this TF templates https://cloud.google.com/run/docs/about-execution-environments

**Comment by bpallares** [comment]
> There is available gen2 in preview which is not possible to select using this TF templates [cloud.google.com/run/docs/about-execution-environments](https://cloud.google.com/run/docs/about-execution-environments)

I was able to create a gen2 with the following :

```tf
  template_annotations = {
    "run.googleapis.com/execution-environment" = "gen2"
  }

  service_annotations = {
    "run.googleapis.com/launch-stage" = "BETA"
  }
```

**Comment by bharathkkb** [comment]
Thanks for the solution @bpallares. @prabhu34 should we add support for this via annotations as bove or do you think should be provider native? I am not familiar with gen2.

**Comment by prabhu34** [comment]
@bharathkkb I tried to use the `generation` metadata as per [this TF documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#generation). But unfortunately TF did not like it. So, setting the generations or execution environment via the `metadata` block is the only option.

We can close this ticket.

**Comment by rquinlivan** [comment]
@prabhu34 That generation field refers to the pod generation, not the Cloud Run execution environment generation.

**Comment by travigd** [comment]
Was also able to do this with
```hcl

resource "google_cloud_run_service" "..." {
  ...
  template {
    ...
    metadata {
      annotations = {
        "run.googleapis.com/execution-environment" = "gen2"
      }
    }
  }
}
```

Would be really nice to add this to the documentation to save other people from having to go down Google rabbit holes.
