### ISSUE TITLE
Support for revision tag url.

### ISSUE THREAD

**Issue by hsblhsn** [GoogleCloudPlatform/terraform-google-cloud-run#23]
Cloud run supports tagging a revision to create a unique url for the revision. The url will always point to an exact revision.

The gcloud command for it 

```sh
gcloud beta run services update --tag=test ....
```

But I could not find it anywhere in the terraform module. Is it there or am I missing something?

**Comment by prabhu34** [comment]
I do not find the support for adding tags in the [Terraform Resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#argument-reference).

Raise the issue in Terraform provider.

**Comment by bharathkkb** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/10341 for tracking provider
