### ISSUE TITLE
Mapping two subdomains to the same service

### ISSUE THREAD

**Issue by enmanuelmoreira** [GoogleCloudPlatform/terraform-google-cloud-run#67]
Hi guys, viewing the examples I won't find a way to mapping domain and subdomain in the same module

Example: I have enmanuelmoreira.com which mapping to root srv and www mapping as well to root srv, but i am able to mapping just the root domain.

Any help is welcome.

Regards.

**Comment by enmanuelmoreira** [comment]
Hi @amandakarina, it is not related with secure-cloud-run-core. I'm triying to deploy a couple of single cloud run services.

**Comment by prabhu34** [comment]
@enmanuelmoreira this module should be used to create a single Cloud Run service mapping to a single domain (it could be domain say example.com or subdomain service1.example.com).

If there are multiple services, use maps and loops to create multiple services with their respective domain maps.
