### ISSUE TITLE
Add tag support in traffic_split

### ISSUE THREAD

**Issue by anassid** [GoogleCloudPlatform/terraform-google-cloud-run#71]
Terraform has `tag` attribute under `traffic` object that seems to be missing from `traffic_split` of this module

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-add-tag

**Comment by juanspinelli** [comment]
it’s a necessary parameter to create revisions and be able to enter the url the tag we need

![image](https://user-images.githubusercontent.com/47563834/197036615-f00f7320-a2fe-4685-ad0d-3d82638495e9.png)
